version: "3.8"

services:
  rabbitmq:
    container_name: mdcc_sd_rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    container_name: mdcc_sd_postgres
    image: postgres:14-alpine
    volumes:
      - mdcc_sd_db_storage:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mdcc_sd_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5433:5432"

  backend:
    container_name: mdcc_sd_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app:cached
    command: ["bash", "./entrypoint.dev.sh"]
    restart: on-failure
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  celery:
    container_name: celery
    platform: linux/amd64
    build:
      context: ./mdcc_sd_backend
      dockerfile: docker/celery/dev/Dockerfile
    # command: [ "bash", "./docker/celery/dev/entrypoint.dev.sh" ]
    command: python3 -m celery -A celery_re:app worker -E
    healthcheck:
      test: ["CMD", "venv/bin/python3", "-m", "celery", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./mdcc_sd_backend:/usr/src/app/:cached
      - ./mdcc_sd_backend:/mdcc_sd_backend:cached
    env_file: mdcc_sd_backend/docker/.env
    depends_on:
      - postgres
      - rabbitmq
      - mdcc_sd_backend

  celery_beat:
    container_name: celery_beat
    platform: linux/amd64
    build:
      context: ./mdcc_sd_backend
      dockerfile: celery_beat.prod.Dockerfile
    command: venv/bin/python3 -m celery -A celery_re:app beat -l INFO
    env_file: mdcc_sd_backend/docker/.env
    depends_on:
      - celery

  frontend:
    container_name: mdcc_sd_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
    restart: on-failure
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mdcc_sd_db_storage:
  rabbitmq_data:
  celery_data:
  celery_beat_data:
