import os

from dotenv import load_dotenv

load_dotenv()

POSTGRES_USER = os.environ.get("POSTGRES_USER")
POSTGRES_HOST = os.environ.get("POSTGRES_HOST")
POSTGRES_PORT = os.environ.get("POSTGRES_PORT")
print(f"POSTGRES_PORT: {POSTGRES_PORT}")
POSTGRES_DATABASE = os.environ.get("POSTGRES_DB")
print(f"POSTGRES_DATABASE: {POSTGRES_DATABASE}")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
print(f"POSTGRES_PASSWORD: {POSTGRES_PASSWORD}")

AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_S3_CUSTOM_DOMAIN = os.environ.get("AWS_S3_CUSTOM_DOMAIN")
DYNAMODB_REGION = os.environ.get("DYNAMODB_REGION")
DYNAMODB_TABLE_NAME = os.environ.get("DYNAMODB_TABLE_NAME")

RABBITMQ_HOST = os.environ.get("RABBITMQ_HOST")
RABBITMQ_PORT = int(os.environ.get("RABBITMQ_PORT", "5672"))
RABBITMQ_USER = os.environ.get("RABBITMQ_USER")
RABBITMQ_PASSWORD = os.environ.get("RABBITMQ_PASSWORD")
RABBITMQ_QUEUE_NAME = os.environ.get("RABBITMQ_QUEUE_NAME")
RABBITMQ_QUEUE_NAME_T2 = os.environ.get("RABBITMQ_QUEUE_NAME_T2")

AWS_ACCESS_KEY_ID_ENV = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY_ENV = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME_ENV = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME_ENV = os.environ.get("AWS_S3_REGION_NAME")
AWS_S3_CUSTOM_DOMAIN_ENV = os.environ.get("AWS_S3_CUSTOM_DOMAIN")
AWS_ALB_DOMAIN_ENV = os.environ.get("AWS_ALB_DOMAIN")

DYNAMODB_REGION_ENV = os.environ.get("DYNAMODB_REGION")
DYNAMODB_TABLE_NAME_ENV = os.environ.get("DYNAMODB_TABLE_NAME")


SNS_TOPIC_ARN = os.environ.get("SNS_TOPIC_ARN")

USE_S3_ENV = os.environ.get("USE_S3")

DEBUG_MODE = os.environ.get("DEBUG_MODE")

SERVICE_API_TOKEN = os.environ.get("SERVICE_API_TOKEN")
