# Generated by Django 5.2.7 on 2025-11-11 01:38

import products_api.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_api", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        storage=products_api.storage_backends.PublicMediaStorage(),
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadPrivate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        storage=products_api.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
