# Generated by Django 5.2.7 on 2025-11-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_api", "0003_upload_uploadprivate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_bw_s3_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
