# Generated by Django 5.2.7 on 2025-12-20 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="private_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_image",
                to="posts_api.uploadprivate",
            ),
        ),
        migrations.AddField(
            model_name="posts",
            name="public_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_image",
                to="posts_api.upload",
            ),
        ),
    ]
