# Generated by Django 5.2.7 on 2025-12-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_api", "0002_posts_private_image_posts_public_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="private_image",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="public_image",
        ),
    ]
