# Generated by Django 5.2.7 on 2026-01-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_api", "0003_remove_posts_private_image_remove_posts_public_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="uploadprivate",
            name="file",
            field=models.FileField(upload_to="private/"),
        ),
    ]
