# Generated by Django 5.2.7 on 2026-01-08 21:23

import posts_api.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_api", "0004_alter_upload_file_alter_uploadprivate_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(
                storage=posts_api.storage_backends.PublicMediaStorage(), upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="uploadprivate",
            name="file",
            field=models.FileField(
                storage=posts_api.storage_backends.PrivateMediaStorage(), upload_to=""
            ),
        ),
    ]
